### PR TITLE
Added db schemas and seed file.

### PR DESCRIPTION
**Pull request by jhou12**
@manedurphy 
@pauly-van 
@slava000 

If you need to get a code review done, can you guys take a look at my seeding script for the Reviews module and lmk if it's good to go? I went over it briefly with Alex in OH and he said the process looks good, and it seems to function as it's supposed to, just want to make sure the code is clear and well-organized. Thanks.

### CODE REVIEW

**Comment by jhou12** [comment]
@manedurphy 
@pauly-van 
@slava000 

Also separate code review if you want but can you look at my fakeData.js functions and lmk if anything is unclear, they are also used in my seeding script. Thanks!

**Comment by manedurphy** [comment]
I noticed in the seed script for reviews that you averaged all categories to calculate the overall average, but I think I remember in class we said that the overall rating was separate from the individual category ratings.

**Comment by jhou12** [comment]
@manedurphy Yes I was a bit confused about what we heard in class too, but I went back and calculated averages for a few more properties and found that they did correlate to the overall average, so I used that. Lmk if you think there's a better way to find the overall score, I'd be happy to modify the calculation. Thanks for the note!

**Comment by jhou12** [comment]
@manedurphy Just made a commit and changed the overall score to be generated randomly like the other 6 metrics instead of calculated as an average, thanks for the tip!

**Pull request merged**
